### ISSUE TITLE
リマインダーの削除ができない(登録者本人なのに…

### ISSUE THREAD

**Issue by Homara8524** [tetsuya-ki/discord-reminderbot#40]
ファイル容量が8MBに差し迫り新規リマインダー登録ができなくなったため削除を実行しようとしたが
BOT登録者本人も、サーバー管理者本人もどちらもコマンドを入力しても受付ず、エラーで帰ってくる
![IMG_3130](https://user-images.githubusercontent.com/101489229/158044082-3c6772ae-3d25-41ba-b05d-b0122d634677.png)
。

**Comment by Homara8524** [comment]
一応経緯だけサクッと説明すると、昨日このBOTをみつけてサーバーに導入（なお導入時５～６回エラーで追加できず、何度か試しているうちに急に導入に成功）。
めっちゃ便利なBOTでありがたい～！と設定していた最中からちょっと挙動がおかしい（構文通りのコマンドを入力するもエラーで帰ってくる(404)。
いくつかは登録に成功して稼働し始めると404で登録できていなかったはずのリマインダー内容も届く（なぜ）
安定したかと思った矢先、新規登録しようとし40005コードのエラーが発生。
ファイル容量確認→7.65MB→急に7.96MBになる
現状このような感じです。
一旦、BOTの再導入を試してみます。

**Comment by tetsuya-ki** [comment]
オーナーが曖昧でしたね。ボットのトークンを作成した人が、あのコマンドでいうオーナーです(Discordの特定のサーバーに導入した人やDiscordのサーバーのオーナーではありません)。
不安定なのはボットを動かしているサーバーが不安定である影響だと思います。
いきなりファイルサイズが増えまくったのは、このボットを使った長文のリマインドが短期間に投稿された(ほとんど荒らしのように)可能性があります。
添付されたファイルを可能でしたら貼っていただけると嬉しいです(中身確認してみます)。

いったん、古いデータの削除を実施しましたので、とりあえず普通に動くと思います。
※おかしな状態のときのデータは消えてしまったかもしれません。。。

**Comment by Homara8524** [comment]
クローズでかまいません。
ご対応ありがとうございます。
ちなみにbotの再導入で改善しました。
お手数おかけしました

**Comment by tetsuya-ki** [comment]
お返事ありがとうございます。
いいえ。何かありましたらお気軽にお問い合わせください。
（反応がないほうがさびしいので。。。）
