### ISSUE TITLE
repeat_intervalの機能の入力方法について

### ISSUE THREAD

**Issue by butcherxx** [tetsuya-ki/discord-reminderbot#43]
毎日9:00に投稿できるようなbotがないかと探しており、こちらにたどり着きました。
早速使わせていただいております、ありがとうございます！

repeat_interval機能についてですが、こちらの登録を試しているのですが「繰り返し間隔が不正のため、リマインドを登録できませんでした」と出て登録ができません。/rimind-makeで表示されるテンプレートからと、下記のように直接入力の両方を試しております。
入力方法に不備がありますでしょうか。repeat_intervalを外せば登録はできます。

/remind-make date:0705 time:12:41 message:テスト投稿 repeat_interval:平日

〇やりたいこと
理想は平日のAM9:00にメッセージを投稿したいと考えております。
毎日手動で7/2、7/3と1件ずつ登録していくのが手間なので、理想は平日というカテゴリーで登録をかけたいのですがエラーが解消できませんので、質問させていただきました。

**Comment by tetsuya-ki** [comment]
日付の書式が違うようです。07/05または07-05と書いてください。数字で指定もできますが、N日後的な意味になったと思います。
> /remind-make date:07/05 time:12:41 message:テスト投稿 repeat_interval:平日

**Comment by butcherxx** [comment]
早々にご回答いただきありがとうございます。
おかげで解決いたしました。早速使わせていただきます。

repeat_intervalをいれないと、日付が0705でも登録できたのですが、repeat_intervalを入れると07/05と正しく入力が必要になっており見落としておりました。

**Comment by tetsuya-ki** [comment]
4桁の数字(0705)だとよくわからない日付で登録されていたので、先頭に年数(2022など)を付与するようにしました。
1-3桁の数字の場合、現在年月+数字として登録するように変更しています(今までは1桁のみの処理だった)

以下で対処したため、クローズします。
https://github.com/tetsuya-ki/discord-reminderbot/commit/086b4414c05b41dd8facf80bcc95601541e4a520
