### ISSUE TITLE
予約投稿の時間がズレることがある

### ISSUE THREAD

**Issue by butcherxx** [tetsuya-ki/discord-reminderbot#45]
平日の9時、12時、15時に予約投稿をし、repeatの機能で自動で再登録、という形で使わせていただいております。

普段は問題なく稼働しているのですが、週に1～2度ほど、予約投稿が行われずに、17時過ぎとか終わってから順次9時、12時、15時の投稿がされていくといった事象が起きております。

こちらを解消したいのですが、この投稿時間は何の時間を参照しているのでしょうか。
Discord側の設定に依存するものでしょうか。

**Comment by tetsuya-ki** [comment]
わたしが作ったBot(認証済みのものや、認証されていないもの)については解消されないものとおもいます。
Discord側の設定に依存しているものではありません。

どこかに書いた気もしますが、いくつかのパターンによってBotが停止します。
Botが再開するまではリマインドが送られません。
再開した後古いものを含めて順次リマインドしていきます。

パターンは以下のようなものがあります。なお、わたしの作ったBotはreplitでうごいています。
（１）replitが不調
（２）replitの該当Botが起動していない
（３）クラウドフレアから一時BAN(replitは利用者でIP共有なのでBANされやすい)
（４）Discordから一時BAN(replitは利用者でIP共有なのでBANされやすい)

沢山の人が使っているので（３）や（４）が発生しやすい状態なのだと思われます。
自分ひとりで使うようにBotを作れば解消されるものと考えています。

今後処理を改善して負荷を下げることはできるかもしれませんが、
replitで動かしている都合上難しそうなイメージがあります。

上に書いたようなことと事象が違う場合
17:0xとか中途半端な時間ではなくタイムゾーンがずれているかのような状態になっているのであれば、
バグだと思います。

**Comment by tetsuya-ki** [comment]
以下のBotの方だとうちのPCが壊れない限りはちゃんと動いてくれると思います。
Botのせいというより動かす環境面の話題なのでクローズさせていただきます。
![image](https://user-images.githubusercontent.com/64536338/194218061-67c786cf-74fa-4593-9da0-dbda7fb4edf7.png)
