### ISSUE TITLE
メッセージの改行について

### ISSUE THREAD

**Issue by Moco5232** [tetsuya-ki/discord-reminderbot#48]
こちらのreminderbotを使用させていただいております。
いつもありがとうございます。
こちら/remind-makeのmessageで改行を使用する方法はございますでしょうか？

**Comment by tetsuya-ki** [comment]
現状ないと思います(多分)。何かしらの方法で入力できるように検討してみます。

対応するなら何かしないとだめそうです
- <改行>などを改行扱いする(Bot側でメッセージ送信時に変換する+説明文に買いておく)
- モーダルでmessageを入力させるよう変更？

**Comment by tetsuya-ki** [comment]
@Moco5232 reminder-bot#6040 を使用している場合は以下のいずれかの文字列で改行されるように対応しました。
(モーダルだとやり方が理解しやすいですが煩雑ですし、スラッシュコマンド側で改行が対応した時悲しくなるのでやめました/説明文にも一応書いたので許してください)
![image](https://user-images.githubusercontent.com/64536338/194785952-290de492-04d2-415a-a33d-33246c7884ff.png)

- `<br>`
- `<改行>`または`【改行】`
- `@@@`

問題なさそうならクローズします。

**Comment by Moco5232** [comment]
こちらご対応ありがとうございます！
とても助かりました。
