### ISSUE TITLE
reminderが使用できなくなりました。

### ISSUE THREAD

**Issue by Moco5232** [tetsuya-ki/discord-reminderbot#52]
こちらのreminderを毎日繰り返しで使用しておりますが、(81)からremindをしなくなりました。
1/3まではリマインドできていましたが、原因をご確認いただけますでしょうか
よろしくお願いいたします。
No. 306908　No. 306910

**Comment by Moco5232** [comment]
新規で登録や、他鯖にて使用してみましたがリマインドしませんでした。

**Comment by tetsuya-ki** [comment]
ご連絡ありがとうございます。こちらはスレッドへのリマインドに対応した際に紛れ込んだバグです。
参照権限がないスレッドをfetchして、エラーとなっていたようです。
現在解消されていると思いますので、ご確認くださいませ。

```python
                        thread = guild.get_channel_or_thread(remind[4])
                        try:
                            if thread is None:
                                thread = await guild.fetch_channel(remind[4]) # こいつがtryの外にいた...
                            remind_msg = await thread.send(msg)
```

**Comment by tetsuya-ki** [comment]
現在、306208が完了した程度らしいので、気長に待ってください...。リマインド1件1秒くらいかかるみたいですね...

**Comment by Moco5232** [comment]
ご対応ありがとうございます。
後ほどリマインドテストしてみます。
