### ISSUE TITLE
リマインダーの消し方を教えてください

### ISSUE THREAD

**Issue by Y4M4BUK1** [tetsuya-ki/discord-reminderbot#61]
こんにちは。今後こちらのBOTを使わせていただきたく、テストをしてみたのですが、
/remind-cancelを実行してもNoが違いますと出てしまい、取り消しすることができませんでした。
こちらの過去ログも見てみたのですが、リマインドキャンセルができるオーナーになるためには
どのような作業が必要なのでしょうか？
テスト自体は自分がサーバーのオーナーで管理者のサーバーで実施しています。
こういったことに詳しくなく、的はずれな質問でしたら大変申し訳ございません。
お手数をおかけしますが、ご返信いただけますと幸いです。
よろしくお願いいたします。

**Comment by tetsuya-ki** [comment]
現時点では本人しかリマインドをキャンセルできない仕様となっております。
/remind-listで表示されたNoのものをキャンセルすることができます。
番号があっているか、再度ご確認ください。
可能なら、スクリーンショットなどで具体的に状況を見せていただけると話が早いです(こんな感じに動くはず)。
![image](https://user-images.githubusercontent.com/64536338/221394607-bffe7b61-59fa-4891-bb19-dc54eede626a.png)

**Comment by Y4M4BUK1** [comment]
早速のご返信ありがとうございます。
繰り返してリマインドを設定した場合、最初の番号と繰り返しの番号が違っていることを
見落としておりました。
きちんとキャンセルすることができました。
お手数をおかけして大変申し訳ございませんでした。
とても便利なBOTですね。今後使わせていただきたいと思います。
大変だとは思いますが、これからも頑張ってください。
ありがとうございました。
