### ISSUE TITLE
一時的なリマインドキャンセル機能

### ISSUE THREAD

**Issue by ch1ma** [tetsuya-ki/discord-reminderbot#64]
一時的なリマインドキャンセル機能（もしくは2種の繰り返し間隔設定）があるとありがたいです。
例として、［毎日］［6:00］から［1時間］毎に送信されるリマインドを作成し、その日のリマインドをキャンセルしても翌日にはまた同じリマインドが再開される、というような事ができると助かります。

**Comment by tetsuya-ki** [comment]
自分も、たまにこの機能欲しいなって思ってました。珍しくリマインドされるタスクが終わってる場合など(終わってるのにリマンドされちゃうな...と)。

スキップ機能という位置付けが良さそうです。nextは[0-9]dやyyyy-mm-dd等の日付、または、time同様の指定ができる感じ。デフォルトは1d(1日後)みたいな雰囲気。
`/remind-skip <id(必須)>  <next(オプション)>`

処理
1. 該当のidのステータスを`SKIP`にする
2. 次のリマインドをnextに従って作成する(next未指定の場合は1dとする)

懸念点
1dの解釈について。0時から1時間ごとにリマインドしている場合1日後で嬉しいのはどちらだろうとも思います。3/19 15:01でやった場合に、(2)を採用しようと考えているけれど、それで使い勝手がいいのかどうか。
(1)次の日0時以降 → 3/20 0:00
(2)`/remind-skip`した対象の24時間後以降 → 3/20 16:00

何らかの形で対応したいとは思います。

**Comment by tetsuya-ki** [comment]
@ch1ma さんへ
デフォルトは1回スキップとして実装しました。
使い方はREADME.md(developブランチ)に記載しています。
https://github.com/tetsuya-ki/discord-reminderbot/tree/develop#remind-skip

下記の認証されたreminder-botを使っている場合はもう使えるはずですので、試して見てください。
![image](https://user-images.githubusercontent.com/64536338/226564709-96df22ec-e70e-4530-9e30-74a5391eaff1.png)
