### ISSUE TITLE
日をまたぐリマインド登録について

### ISSUE THREAD

**Issue by mimasaka** [tetsuya-ki/discord-reminderbot#74]
ちょっとしたリマインドで便利に活用させてもらってます。
`/remind-make`コマンドの`time`オプションにてxx時間後(分後)で登録ができますが日をまたぐと過去の日付で登録されてしまうようです。

例:1/1 23:00に`date`:0 `time`:2hで登録
想定の動き:1/2 1:00で登録
実際の動き:1/1 1:00で登録

過去の日付になると登録して数秒後にリマインドが来て「あれ？」となったので
念の為ご報告させていただきました。

`date`を1にすることで想定の動きとなりますので
対応可否はお任せいたします。
※仕様ならばクローズで問題ありません

**Comment by tetsuya-ki** [comment]
ご指摘ありがとうございます。対応してみました。
![image](https://github.com/tetsuya-ki/discord-reminderbot/assets/64536338/a50f931d-ff2f-4281-8675-e47a134424e5)

**Comment by mimasaka** [comment]
私のほうでも日が跨いだ際も想定通りの動きとなっていることを確認しました。

こちらのIssueはクローズで問題ありません。
早急にご対応いただきありがとうございました。
