### ISSUE TITLE
時間がズレて投稿されます

### ISSUE THREAD

**Issue by miyakopubl** [tetsuya-ki/discord-reminderbot#78]
以前からdiscordのイベント用に使わせていただいてます。

今までは入力通り動いていたのですが、昨日使ったところ設定時間から10数分〜20数分遅れで投稿されるようになってしまいました。
この10〜20数分とはバラバラで、18分のときもあれば25分のときもあります。
しかし30分を超えることはないようです。
タイムゾーンでズレるのだとしたら1時間ズレだと思うのでこの誤差がなぜ起こるのかわかりません。

原因や改善方法などお心当たりあれば教えてください。
よろしくお願いいたします。

**Comment by tetsuya-ki** [comment]
昨日あたり、大量に1分間隔のリマイドを登録したユーザーが存在したらしいです。
BANしたので一旦は大丈夫だと思います。
1分間隔は5回までなど制限を加えようと思います。なにかあればまたIssueかdiscordサーバーまで連絡ください。

**Comment by tetsuya-ki** [comment]
Botのせいというより人間さんのせいなのでクローズします。
developブランチに対策を入れたので必要ならこちらを使用して下さいませ。

**Comment by miyakopubl** [comment]
ご対応ありがとうございます。
再度テストし時間通りに投稿されることを確認いたしました。
