### ISSUE TITLE
メッセージの改行について

### ISSUE THREAD

**Issue by Shizuku1126** [tetsuya-ki/discord-reminderbot#93]
こちらのreminderbotを使用させていただいております。
いつもありがとうございます。

<br>
<改行>または【改行】
@@@

上記のいずれでも改行が反映されない状況です。
文字数などの制限はありますか？

お手数おかけしますがお返事くださりますと幸いです。
よろしくお願いいたします。

**Comment by tetsuya-ki** [comment]
@Shizuku1126 再現しませんでした。ためしにその文章でやってみましたが。
昔のスラッシュコマンドだと改行できなかったのでそういう機能をつけましたが、もし普通に改行できるのであれば改行いただければと思います。
<br>でも改行と認識されたと思うので、そちらも試すといいかもしれません。

![Screenshot_20241205-210000.png](https://github.com/user-attachments/assets/181e4ab0-4fc5-44f2-8f8b-25d700e79ea8)

![markup_1000006601.png](https://github.com/user-attachments/assets/41dc8931-60f7-4df2-9bda-72d2200227a7)

もし、詳しく知られていただきたい場合は、該当リマインドのNoを教えていただければわかるかもしれません(時期によってはデータが削除されてることもありえますが)

**Comment by Shizuku1126** [comment]
返信くださりありがとうございます。

<br>でも試してみたのですが改行されませんでした。
該当リマインドのNoは「No. 1951580」になります。

お手すきの時にご確認いただくことは可能でしょうか？
お手数おかけしますがよろしくお願いいたします。

![image](https://github.com/user-attachments/assets/ac4fe0e0-647a-4d2e-9ebb-8ae5c50a3184)

**Comment by tetsuya-ki** [comment]
もしかして、リマインド確認時の話をされていますか？　リマインド確認時は改行の変換はしてないです。
実際にリマインドされるときに改行へ変換しています。わかりづらくてすみません。。直近でリマインド作ってみていただき、改行されることを確認いただければ幸いです。リスト時に改行が変換された方がいいんじゃないか、という話でしたらなんかオプションで指定できるようにしてもいいかもです。

**Comment by Shizuku1126** [comment]
返信くださりありがとうございます！

直近ででリマインド作成し試してみたところ、無事反映されました！
初めて、botの設定をしてわからないことだらけだったので、すぐにご回答いただけて本当に助かりました！
改めてありがとうございました。

引き続きよろしくお願いいたします！

**Comment by tetsuya-ki** [comment]
よかったです〜。人気の時間帯だとリマインドが多すぎて数分遅れるかもしれないですが、、、適当なメモ程度に使っていただけたら幸いです。
